---
abstract: 'Class for GraphViz image from SCPN schema.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SCPN-Schema-GraphViz
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.03
  GraphViz2: 0
  Mojo::Exception: 0
  Scalar::Util: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=SCPN-Schema-GraphViz
  homepage: https://github.com/tupinek/SCPN-Schema-GraphViz
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/SCPN-Schema-GraphViz
version: '0.01'
